### ISSUE TITLE
Create a sample HMI file for testing purpose of library

### ISSUE THREAD

**Issue by s-celles** [raffmont/pynextion#11]
Hello,

I think a sample HMI file for testing library and widgets is required.

I did previously
https://github.com/scls19fr/pynextion/blob/7d9f6369cdc602d6e6db5993108daa4581e381c9/test_gui.HMI
when working on a Julia Nextion library (currently unpublished)

Kind regards

**Comment by raffmont** [comment]
Right!
On Monday I'll back in the lab.
I'll share one of mine too.

**Comment by s-celles** [comment]
Any news?

**Comment by s-celles** [comment]
@raffmont Could you approach your boat from the coast? We can't hear you. :laughing:

**Comment by undera** [comment]
+1 to have example (from newbie)

**Comment by s-celles** [comment]
HMI example is good both because it can help newbies to understand how library is working but it's also  interesting as this HMI example can be used for testing the library itself.

I'm sad not to have any response and that my branch https://github.com/scls19fr/pynextion/tree/devel
haven't been discussed...  ( https://github.com/python-nextion/pynextion/pull/12 )

Even simple PEP8 PR like https://github.com/python-nextion/pynextion/pull/13 or continuous integration PR like https://github.com/python-nextion/pynextion/pull/16 can't be merged

I thinking leaving this https://github.com/python-nextion/ GH org because nothing good is coming here.

**Comment by undera** [comment]
Leaving in favor of what?

**Comment by s-celles** [comment]
https://github.com/py3-nextion/pynextion
