### ISSUE TITLE
Merge code from forks

### ISSUE THREAD

**Issue by s-celles** [raffmont/pynextion#7]
Hello,

[some forks](https://github.com/raffmont/pynextion/network/members) have Python 2/3 support and have made some cleanup.

Maybe merging should be considered?

Pinging @glebovmaksim @fake-name

Kind regards

**Comment by fake-name** [comment]
The changes I made are pretty large-scale and aggressive. I also didn't spend any time on py2k (because you shouldn't be using it at all, at this point). 

I mean, it could be merged, but it'd break a lot of existing stuff.

**Comment by s-celles** [comment]
I personally don't need Python 2.x support anymore.

**Comment by fake-name** [comment]
My point was more I went in and renamed methods and shit for consistency.  I moved everything from CamelCast to under_score_names.

**Comment by s-celles** [comment]
I'm wondering if a python-nextion Github organization shouldn't be created to give more hightlight to active forks. What is your opinion @raffmont @glebovmaksim @fake-name ?
I have a HMI file with several widgets (all Nextion widgets I think). Such a file could be used as an example / for testing purpose. I can submit a PR for that but I will do it only in a repository belonging to several contributors.

**Comment by raffmont** [comment]
@scls19fr  @fake-name 
I could add you as contributor, so you could manage your changes directly.
What about It?

**Comment by s-celles** [comment]
Sorry @raffmont but I'm not sure that's the right approach!

We should define an organisation name https://github.com/python-nextion for example (or something else) and you can go to https://github.com/raffmont/pynextion/settings

- Danger Zone
  - Transfer ownership
Transfer this repository to another user or to an organization where you have the ability to create repositories.

**Comment by raffmont** [comment]
@scls19fr I know,
We have the organisation!

**Comment by s-celles** [comment]
Thanks @raffmont for this invite to https://github.com/python-nextion GH org
Could you now transfer ownership of https://github.com/raffmont/pynextion/ to https://github.com/python-nextion (where you are owner)

**Comment by raffmont** [comment]
Thank you so much @scls19fr for your input!
Please, check if everything has been performed correctly.  
I invited @fake-name  too.

**Comment by s-celles** [comment]
Great.
@raffmont What is your opinion about dropping Python 2.x support and concentrate effort on Python 3.x?
Let's wait a PR from @fake-name 

I think you should enable Travis for https://travis-ci.com/profile/python-nextion
so we could run unit tests, run PEP8 checks on Travis side.

**Comment by raffmont** [comment]
@scls19fr sure!
I'll do it as the workshop I'm attending will finish.
About Python 2 support. I think that is the time to step over with Python 2 and embrace the 3...

**Comment by fake-name** [comment]
See https://github.com/python-nextion/pynextion/pull/8

Note that I did all this because I wanted to use the library for debugging a work-project that has ended, so I may not have time to actively focus on it at the moment.
